import {useMemo,useState} from 'react'
import {approveOrder,createOrder,rejectOrder,updateOrderQuantity,convertOfferToOrder,createOffer} from './service'
const d=(v:any)=>v?new Date(v+'T12:00:00').toLocaleDateString('tr-TR'):'—'
const money=(v:any)=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:0}).format(Number(v||0))

type ActionState={type:'change'|'reject'|'convert'|null;row:any|null}
export function OfferOrderCenterPage({orders,offers,exams,institutions,onRefresh}:{orders:any[];offers:any[];exams:any[];institutions:any[];onRefresh?:()=>Promise<void>|void}){
 const[tab,setTab]=useState<'orders'|'offers'|'new'|'newOffer'>('orders'),[state,setState]=useState('all'),[q,setQ]=useState(''),[msg,setMsg]=useState('')
 const[inst,setInst]=useState(''),[exam,setExam]=useState(''),[qty,setQty]=useState(1),[notes,setNotes]=useState('')
 const[unitPrice,setUnitPrice]=useState(0),[validUntil,setValidUntil]=useState(''),[overrideReason,setOverrideReason]=useState('')
 const[action,setAction]=useState<ActionState>({type:null,row:null}),[actionQty,setActionQty]=useState(1),[actionReason,setActionReason]=useState('')
 const filtered=useMemo(()=>orders.filter(x=>(state==='all'||x.deadline_state===state||x.admin_approval===state)&&(!q||`${x.institution_name} ${x.order_no} ${x.exam_name} ${x.publisher}`.toLocaleLowerCase('tr').includes(q.toLocaleLowerCase('tr')))),[orders,state,q])
 const selectedExam=exams.find(x=>x.id===exam)
 const deadlinePassed=!!selectedExam?.last_order_date&&new Date(selectedExam.last_order_date+'T12:00:00')<new Date(new Date().toDateString())
 async function refresh(){await onRefresh?.()}
 function resetForm(){setQty(1);setNotes('');setOverrideReason('');setUnitPrice(0);setValidUntil('')}
 async function add(){try{if(!inst||!exam||qty<=0)throw new Error('Kurum, deneme ve miktar zorunludur.');if(deadlinePassed&&!overrideReason.trim())throw new Error('Son sipariş tarihi geçtiği için yönetici müdahale gerekçesi zorunludur.');await createOrder(inst,exam,qty,notes,overrideReason||undefined);setMsg('Sipariş oluşturuldu ve Admin Onay kuyruğuna gönderildi.');resetForm();await refresh();setTab('orders')}catch(e:any){setMsg(e.message)}}
 async function addOffer(){try{if(!inst||!exam||qty<=0)throw new Error('Kurum, deneme ve miktar zorunludur.');if(unitPrice<0)throw new Error('Birim fiyat geçersiz.');await createOffer(inst,exam,qty,unitPrice,validUntil||undefined,notes);setMsg('Teklif oluşturuldu.');resetForm();await refresh();setTab('offers')}catch(e:any){setMsg(e.message)}}
 function openChange(x:any){setAction({type:'change',row:x});setActionQty(Number(x.quantity||1));setActionReason('')}
 function openReject(x:any){setAction({type:'reject',row:x});setActionReason('')}
 function openConvert(x:any){setAction({type:'convert',row:x});setActionReason('')}
 async function submitAction(){const x=action.row;if(!x||!action.type)return;try{if(action.type==='change'){if(actionQty<1)throw new Error('Geçerli miktar girin.');if(x.deadline_state==='kapali'&&!actionReason.trim())throw new Error('Tarih sonrası değişiklik için gerekçe zorunludur.');await updateOrderQuantity(x.order_item_id,actionQty,actionReason||undefined);setMsg('Miktar güncellendi; sipariş yeniden Admin Onay kuyruğuna alındı.')}if(action.type==='reject'){if(!actionReason.trim())throw new Error('Red gerekçesi zorunludur.');await rejectOrder(x.order_id,actionReason);setMsg('Sipariş reddedildi.')}if(action.type==='convert'){const expired=(x.offer_items||[]).some((i:any)=>i.exams?.last_order_date&&new Date(i.exams.last_order_date+'T12:00:00')<new Date(new Date().toDateString()));if(expired&&!actionReason.trim())throw new Error('Tarih sonrası dönüşüm için gerekçe zorunludur.');const r=await convertOfferToOrder(x.id,actionReason||undefined);setMsg(`Teklif siparişe dönüştürüldü: ${r?.order_no||''}. Admin onayı bekliyor.`);setTab('orders')}setAction({type:null,row:null});setActionReason('');await refresh()}catch(e:any){setMsg(e.message)}}
 async function approve(x:any){try{await approveOrder(x.order_id);setMsg('Sipariş onaylandı; operasyon akışı başlatıldı.');await refresh()}catch(e:any){setMsg(e.message)}}
 function chooseExam(id:string){setExam(id);const e=exams.find(x=>x.id===id);setUnitPrice(Number(e?.unit_price||0));setValidUntil(e?.last_order_date||'')}
 return <section>
  <div className="page-head"><div><h2>Teklif & Sipariş Yönetim Merkezi</h2><p>Tekliften siparişe, kurum talebinden yönetici onayına kadar ticari akışı tek merkezden yönetin.</p></div><div className="oo-head-actions"><button className="secondary" onClick={()=>setTab('newOffer')}>+ Yeni Teklif</button><button onClick={()=>setTab('new')}>+ Yeni Sipariş</button></div></div>
  {msg&&<div className="action-message">{msg}</div>}
  <div className="oo-kpis"><div><span>Toplam Sipariş Kalemi</span><b>{orders.length}</b></div><div><span>Onay Bekleyen</span><b>{orders.filter(x=>x.admin_approval==='bekliyor').length}</b></div><div><span>Son Tarihi Geçen</span><b>{orders.filter(x=>x.deadline_state==='kapali').length}</b></div><div><span>Yaklaşan / Kritik</span><b>{orders.filter(x=>['yaklasiyor','kritik','son_gun'].includes(x.deadline_state)).length}</b></div><div><span>Aktif Teklif</span><b>{offers.filter(x=>!['reddedildi','suresi_doldu','siparise_donustu'].includes(x.status)).length}</b></div></div>
  <div className="oo-tabs"><button className={tab==='orders'?'active':''} onClick={()=>setTab('orders')}>Siparişler</button><button className={tab==='offers'?'active':''} onClick={()=>setTab('offers')}>Teklifler</button><button className={tab==='new'?'active':''} onClick={()=>setTab('new')}>Yeni Sipariş</button><button className={tab==='newOffer'?'active':''} onClick={()=>setTab('newOffer')}>Yeni Teklif</button></div>
  {tab==='orders'&&<><div className="oo-toolbar"><input placeholder="Kurum, sipariş, deneme ara…" value={q} onChange={e=>setQ(e.target.value)}/><select value={state} onChange={e=>setState(e.target.value)}><option value="all">Tüm Durumlar</option><option value="bekliyor">Admin Onay Bekleyen</option><option value="acik">Sipariş Açık</option><option value="yaklasiyor">Son Tarih Yaklaşıyor</option><option value="kritik">Kritik</option><option value="son_gun">Bugün Son Gün</option><option value="kapali">Sipariş Kapandı</option></select></div>
  <div className="oo-list">{filtered.map(x=><article className={`card oo-card ${x.deadline_state}`} key={x.order_item_id}><header><div><b>{x.institution_name}</b><small>{x.order_no} · {x.source==='kurum'?'Kurum Siparişi':'Yönetici Siparişi'}</small></div><div className="oo-tags"><span>{x.admin_approval}</span><span>{x.deadline_state.replaceAll('_',' ')}</span>{x.admin_override_used&&<span className="override">Yönetici Müdahalesi</span>}</div></header><div className="oo-grid"><div><span>Deneme</span><b>{x.exam_name}</b><small>{x.publisher} · {x.exam_type}</small></div><div><span>Miktar</span><b>{x.quantity}</b>{x.previous_quantity!=null&&<small>Onaylı baz: {x.previous_quantity}</small>}</div><div><span>Birim / Toplam</span><b>{money(x.unit_price)}</b><small>{money(x.line_total)}</small></div><div><span>Son Sipariş</span><b>{d(x.last_order_date)}</b><small>{x.days_to_last_order>=0?`${x.days_to_last_order} gün kaldı`:`${Math.abs(x.days_to_last_order)} gün geçti`}</small></div><div><span>Uygulama</span><b>{d(x.application_date)}</b><small>{x.days_to_exam} gün</small></div></div><footer><button className="secondary" onClick={()=>openChange(x)}>Miktar Değiştir</button>{x.admin_approval==='bekliyor'&&<><button onClick={()=>approve(x)}>Onayla</button><button className="danger" onClick={()=>openReject(x)}>Reddet</button></>}</footer>{x.admin_override_used&&x.last_admin_override_reason&&<div className="oo-override-note">Tarih sonrası yönetici müdahalesi: {x.last_admin_override_reason}</div>}</article>)}</div></>}
  {tab==='offers'&&<div className="oo-list">{offers.map((x:any)=><article className="card oo-card" key={x.id}><header><div><b>{x.institutions?.name||'Kurum'}</b><small>{x.offer_no||x.id.slice(0,8)}</small></div><span>{x.status}</span></header><div className="oo-grid"><div><span>Teklif Tarihi</span><b>{d((x.offer_date||x.created_at)?.slice?.(0,10))}</b></div><div><span>Geçerlilik</span><b>{d(x.valid_until)}</b></div><div><span>Toplam</span><b>{money(x.total_amount)}</b></div><div><span>Kalem</span><b>{x.offer_items?.length||0}</b></div></div>{!['reddedildi','suresi_doldu','siparise_donustu'].includes(x.status)&&<footer><button onClick={()=>openConvert(x)}>Siparişe Dönüştür</button></footer>}</article>)}</div>}
  {tab==='newOffer'&&<div className="card oo-form"><h3>Yeni Teklif Oluştur</h3><label>Kurum<select value={inst} onChange={e=>setInst(e.target.value)}><option value="">Kurum seçin</option>{institutions.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Deneme<select value={exam} onChange={e=>chooseExam(e.target.value)}><option value="">Deneme seçin</option>{exams.map(x=><option key={x.id} value={x.id}>{x.publisher} · {x.exam_name} · {d(x.application_date)}</option>)}</select></label><label>Miktar<input type="number" min="1" value={qty} onChange={e=>setQty(Number(e.target.value))}/></label><label>Birim Fiyat<input type="number" min="0" step="0.01" value={unitPrice} onChange={e=>setUnitPrice(Number(e.target.value))}/></label><label>Geçerlilik Tarihi<input type="date" value={validUntil} onChange={e=>setValidUntil(e.target.value)}/></label><label>Not<textarea value={notes} onChange={e=>setNotes(e.target.value)} /></label><button onClick={addOffer}>Teklifi Oluştur</button></div>}
  {tab==='new'&&<div className="card oo-form"><h3>Yeni Sipariş Oluştur</h3><label>Kurum<select value={inst} onChange={e=>setInst(e.target.value)}><option value="">Kurum seçin</option>{institutions.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Deneme<select value={exam} onChange={e=>chooseExam(e.target.value)}><option value="">Deneme seçin</option>{exams.map(x=><option key={x.id} value={x.id}>{x.publisher} · {x.exam_name} · {d(x.application_date)} · Son: {d(x.last_order_date)}</option>)}</select></label><label>Miktar<input type="number" min="1" value={qty} onChange={e=>setQty(Number(e.target.value))}/></label>{deadlinePassed&&<label>Yönetici Müdahale Gerekçesi<textarea value={overrideReason} onChange={e=>setOverrideReason(e.target.value)} placeholder="Son sipariş tarihi sonrası işlem gerekçesi" /></label>}<label>Not<textarea value={notes} onChange={e=>setNotes(e.target.value)} /></label><button onClick={add}>Siparişi Oluştur</button><p className="oo-help">Yeni sipariş, kaynağı ne olursa olsun Admin Onay kuyruğuna düşer.</p></div>}
  {action.type&&<div className="modal-backdrop"><div className="card modal-card"><h3>{action.type==='change'?'Sipariş Miktarını Değiştir':action.type==='reject'?'Siparişi Reddet':'Teklifi Siparişe Dönüştür'}</h3>{action.type==='change'&&<label>Yeni Miktar<input type="number" min="1" value={actionQty} onChange={e=>setActionQty(Number(e.target.value))}/></label>}<label>{action.type==='reject'?'Red Gerekçesi':'Yönetici Notu / Gerekçe'}<textarea value={actionReason} onChange={e=>setActionReason(e.target.value)} /></label><div className="modal-actions"><button className="secondary" onClick={()=>setAction({type:null,row:null})}>Vazgeç</button><button onClick={submitAction}>İşlemi Tamamla</button></div></div></div>}
 </section>
}