import { useMemo, useState } from 'react'
import type { Exam } from '../exam-import/types'
import type { OperationalSignal } from './types'

function days(date:string|null){if(!date)return null;const [y,m,d]=date.split('-').map(Number);const t=new Date();const a=new Date(t.getFullYear(),t.getMonth(),t.getDate());return Math.ceil((new Date(y,m-1,d).getTime()-a.getTime())/86400000)}
function warning(e:Exam,s?:OperationalSignal){const left=days(e.last_order_date);if((s?.delivery_risk_count||0)>0)return 'Operasyon Riski';if(left===0)return 'Bugün Son Gün';if(left!==null&&left<0)return 'Sipariş Kapandı';if(left!==null&&left<=3)return 'Kritik';if(left!==null&&left<=7)return 'Yaklaşıyor';const app=days(e.application_date);if(app!==null&&app<=7&&app>=0)return 'Uygulama Yaklaşıyor';return 'Normal'}
export function ExamCalendar({exams,signals,onNavigate,onOpenOrders,onOpenOperations}:{exams:Exam[];signals:OperationalSignal[];onNavigate:(x:string)=>void;onOpenOrders:(id:string)=>void;onOpenOperations:(id:string)=>void}){
 const [q,setQ]=useState('');const sm=useMemo(()=>new Map(signals.map(s=>[s.exam_id,s])),[signals]);const filtered=exams.filter(e=>`${e.publisher} ${e.exam_name} ${e.grade_level} ${e.exam_type}`.toLowerCase().includes(q.toLowerCase()))
 const stats={last:filtered.filter(e=>{const d=days(e.last_order_date);return d!==null&&d>=0&&d<=7}).length,week:filtered.filter(e=>{const d=days(e.application_date);return d!==null&&d>=0&&d<=7}).length,closed:filtered.filter(e=>(days(e.last_order_date)??1)<0).length,risk:filtered.filter(e=>(sm.get(e.id)?.delivery_risk_count||0)>0).length}
 return <section><div className="page-title"><div><h1>Deneme Takvimi</h1><p>Tarih yoğunluğu, sipariş son günleri ve operasyon sinyalleri tek ekranda.</p></div><button onClick={()=>onNavigate('Teklif & Sipariş Merkezi')}>Yeni Sipariş / Teklif</button></div><div className="cards"><button className="kpi"><span>Son Sipariş Yaklaşanlar</span><b>{stats.last}</b></button><button className="kpi"><span>Bu Hafta Uygulanacaklar</span><b>{stats.week}</b></button><button className="kpi"><span>Siparişi Kapananlar</span><b>{stats.closed}</b></button><button className="kpi" onClick={()=>onNavigate('Operasyon Merkezi')}><span>Operasyon Riski</span><b>{stats.risk}</b></button></div><div className="toolbar"><input placeholder="Yayın, deneme, kademe veya tür ara" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="table-wrap"><table><thead><tr><th>Yayın / Deneme</th><th>Kademe</th><th>Tür</th><th>Uygulama</th><th>Son Sipariş</th><th>Hedef Teslim</th><th>Kalan Gün</th><th>Fiyat</th><th>Uyarı</th><th>Aksiyon</th></tr></thead><tbody>{filtered.map(e=>{const s=sm.get(e.id);const w=warning(e,s);return <tr key={e.id}><td><b>{e.publisher}</b><small>{e.exam_name}</small></td><td>{e.grade_level}</td><td>{e.exam_type}</td><td>{e.application_date}</td><td>{e.last_order_date||'-'}</td><td>{e.target_delivery_date||'-'}</td><td>{days(e.last_order_date)??'-'}</td><td>{Number(e.unit_price||0).toLocaleString('tr-TR')} TL</td><td><span className={`status ${w.toLowerCase().replaceAll(' ','-')}`}>{w}</span></td><td className="actions"><button onClick={()=>onOpenOrders(e.id)}>Sipariş</button>{(s?.incomplete_operation_count||0)>0&&<button onClick={()=>onOpenOperations(e.id)}>Operasyon</button>}</td></tr>})}</tbody></table></div></section>
}
