import { useMemo,useState } from 'react'
import { createOperationException,markDelivered,startDispatch } from './service'
export function OperationCenterPage({rows,summary,onRefresh,selectedExamId}:{rows:any[];summary:any;onRefresh:()=>Promise<void>;selectedExamId?:string|null}){
 const [busy,setBusy]=useState<string|null>(null);const [modal,setModal]=useState<{kind:'dispatch'|'delivery'|'exception';row:any}|null>(null);const [method,setMethod]=useState('kargo');const [tracking,setTracking]=useState('');const [note,setNote]=useState('');const [exceptionType,setExceptionType]=useState('eksik_teslim')
 const filtered=useMemo(()=>selectedExamId?rows.filter(r=>r.exam_id===selectedExamId):rows,[rows,selectedExamId]); const run=async(id:string,fn:()=>Promise<void>)=>{try{setBusy(id);await fn();await onRefresh();setModal(null)}finally{setBusy(null)}}
 return <section><div className="page-title"><div><h1>Operasyon Merkezi</h1><p>Onaylı siparişlerin ürün yeterliliği, sevk ve teslim süreci.</p></div></div><div className="cards"><div className="kpi"><span>Toplam Operasyon</span><b>{summary?.total||0}</b></div><div className="kpi"><span>Sevke Hazır</span><b>{summary?.ready||0}</b></div><div className="kpi"><span>Dağıtımda</span><b>{summary?.inDistribution||0}</b></div><div className="kpi"><span>Risk</span><b>{summary?.risk||0}</b></div></div>
 <div className="table-wrap"><table><thead><tr><th>Kurum</th><th>Deneme</th><th>Adet</th><th>Hedef Teslim</th><th>Ürün</th><th>Operasyon</th><th>Aksiyon</th></tr></thead><tbody>{filtered.map(r=><tr key={r.operation_id||r.order_id}><td>{r.institution_name}</td><td><b>{r.publisher}</b><small>{r.exam_name}</small></td><td>{r.quantity}</td><td>{r.target_delivery_date||'-'}</td><td>{r.readiness_status||'Kontrol ediliyor'}</td><td>{r.status||'planlandi'}</td><td className="actions">{!['dagitimda','teslim'].includes(r.status)&&<button onClick={()=>{setModal({kind:'dispatch',row:r});setNote('');setTracking('')}}>Sevk Başlat</button>}{r.status==='dagitimda'&&<button onClick={()=>{setModal({kind:'delivery',row:r});setNote('')}}>Teslim Et</button>}<button className="secondary" onClick={()=>{setModal({kind:'exception',row:r});setNote('')}}>Sorun Kaydı</button></td></tr>)}{!filtered.length&&<tr><td colSpan={7}>Operasyon kaydı bulunmuyor.</td></tr>}</tbody></table></div>
 {modal&&<div className="modal-backdrop"><div className="modal"><h3>{modal.kind==='dispatch'?'Sevk Başlat':modal.kind==='delivery'?'Teslimatı Tamamla':'Operasyon Sorunu Kaydet'}</h3><p>{modal.row.institution_name} · {modal.row.exam_name}</p>{modal.kind==='dispatch'&&<><label>Teslim Yöntemi<select value={method} onChange={e=>setMethod(e.target.value)}><option value="kargo">Kargo</option><option value="kurye">Kurye</option><option value="elden">Elden</option><option value="kurum_araci">Kurum Aracı</option><option value="diger">Diğer</option></select></label><label>Takip No<input value={tracking} onChange={e=>setTracking(e.target.value)}/></label></>}{modal.kind==='exception'&&<label>Sorun Türü<select value={exceptionType} onChange={e=>setExceptionType(e.target.value)}><option value="eksik_teslim">Eksik Teslim</option><option value="hasar">Hasar</option><option value="yanlis_urun">Yanlış Ürün</option><option value="iade">İade</option><option value="yeniden_sevk">Yeniden Sevk</option><option value="diger">Diğer</option></select></label>}<label>Açıklama<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><div className="modal-actions"><button onClick={()=>setModal(null)}>Vazgeç</button><button disabled={busy===modal.row.operation_id||(modal.kind==='exception'&&!note.trim())} onClick={()=>run(modal.row.operation_id,()=>modal.kind==='dispatch'?startDispatch(modal.row.operation_id,method,tracking||null,note||null):modal.kind==='delivery'?markDelivered(modal.row.operation_id,note||null):createOperationException(modal.row.operation_id,exceptionType,note.trim()))}>Kaydet</button></div></div></div>}
 </section>
}
